### ISSUE TITLE
Supported hardware platform

### ISSUE THREAD

**Issue by prasanpro** [hj91/IIoT-Gateway#1]
Which hardware platform is supported for this distribution? In order to take inputs from different kinds of hardware interfacing, there should be clarification for hardware support. Please mention it, does has support for Raspberry Pi?

**Comment by hj91** [comment]
This os does not work on raspberry pi platform. If user has got rs-232, rs-485 ports installed on his machine, then they can directly connect their field devices to the server or vm with this gateway installed on it. 

With latest developments, it is recommended to use serial modbus TCP hardware converters that can send serial port data over ethernet. Raspberry pi with its gpio pins can be used as a serial to ethernet converter, however that software is beyond my scope as of today.
